# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_app

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics', '~> 6.2'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/MLVision'
pod 'Firebase/Core'
pod 'Firebase/MLVisionTextModel'
pod 'GoogleMLKit/TextRecognition'
pod 'SwiftEventBus', :tag => '5.0.1', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  target 'ios_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_appUITests' do
    # Pods for testing
  end

end
