/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    13
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_ota_control                    21
#define gattdb_hall_state                     24
#define gattdb_hall_field_strength            27
#define gattdb_hall_control_point             30
#define gattdb_aio_digital_in                 33
#define gattdb_aio_num_of_digitals_in         36
#define gattdb_aio_digital_out                38
#define gattdb_aio_num_of_digitals_out        40
#define gattdb_es_temperature                 43
#define gattdb_es_humidity                    45
#define gattdb_es_uvindex                     47
#define gattdb_es_ambient_light               49
#define gattdb_batt_measurement               52
#define gattdb_power_source_type              56
#define gattdb_imu_acceleration               59
#define gattdb_imu_orientation                62
#define gattdb_imu_control_point              65


#endif // __GATT_DB_H
